services:
  # Laravel application container (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: quickform
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      # Mount project code for live reload
      - codefiles:/var/www
    env_file:
      - .env
    networks:
      - quickform-network
    depends_on:
      postgres:
        condition: service_healthy

  # Nginx web server
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - codefiles:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - quickform-network
    depends_on:
      app:
        condition: service_started

  # PostgreSQL database
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_DB=quickform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - quickform-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quickform"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # WebSocket server (Laravel Reverb)
#  websocket:
#    image: quickform
#    command: >
#        sh -c "echo 'Waiting 10s for app…' && sleep 10 \
#               && php artisan reverb:start --host=0.0.0.0 --port=6001"
#    working_dir: /var/www
#    volumes:
#        - codefiles:/var/www
#    env_file:
#      - .env
#    ports:
#      - "6001:6001"
#    networks:
#      - quickform-network
#    depends_on:
#      postgres:
#        condition: service_healthy
#      app:
#        condition: service_started

  # Queue worker
  queue:
    image: quickform
    command: >
        sh -c "echo 'Waiting 10s for app…' && sleep 10 \
               && php artisan queue:work --sleep=3 --tries=3 --timeout=90"
    working_dir: /var/www
    volumes:
        - codefiles:/var/www
    env_file:
      - .env
    networks:
      - quickform-network
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_started

volumes:
  pgdata:
  codefiles:

networks:
  quickform-network:
