name: Deploy to Sandbox

on:
  push:
    branches:
      - sandbox
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sandbox

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Generate .env file
        run: |
          echo "${{ vars.APP_ENV }}" > .env

      - name: Debug .env file
        run: |
          echo "Checking if .env file was generated:"
          ls -la .env
          echo ""
          echo "Checking if .env contains PostgreSQL variables:"
          grep -i postgres .env || echo "No PostgreSQL variables found in .env"
          echo ""
          echo "First few lines of .env file:"
          head -10 .env

      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
        run: |
          # Copy the generated .env file to the server
          scp .env ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}/.env

          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ${{ secrets.VPS_PATH }}

            # Pull latest changes
            git fetch origin
            git reset --hard origin/sandbox

            # Build and deploy with Docker Compose
            docker-compose -p quickform_sandbox down
            docker-compose -p quickform_sandbox build --no-cache
            docker-compose -p quickform_sandbox up -d

            # Run database migrations
            docker-compose -p quickform_sandbox exec -T app php artisan migrate --force

            # Clear caches
            docker-compose -p quickform_sandbox exec -T app php artisan config:clear
            docker-compose -p quickform_sandbox exec -T app php artisan cache:clear
            docker-compose -p quickform_sandbox exec -T app php artisan route:clear
            docker-compose -p quickform_sandbox exec -T app php artisan view:clear

            # Optimize for production
            docker-compose -p quickform_sandbox exec -T app php artisan config:cache
            docker-compose -p quickform_sandbox exec -T app php artisan route:cache
            docker-compose -p quickform_sandbox exec -T app php artisan view:cache

            # Set proper permissions
            docker-compose -p quickform_sandbox exec -T app chown -R www-data:www-data storage bootstrap/cache

            echo "Deployment completed successfully!"
          EOF

      - name: Verify .env file on server
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
        run: |
          echo "Verifying .env file on server:"
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ${{ secrets.VPS_PATH }} && ls -la .env && echo 'PostgreSQL variables in .env:' && grep -i postgres .env || echo 'No PostgreSQL variables found' && echo 'Docker containers:' && docker-compose -p quickform_sandbox ps"

      - name: Health check
        run: |
          sleep 30
          curl -f ${{ secrets.VPS_URL }}/health || exit 1

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Deployment to sandbox successful!"
          else
            echo "❌ Deployment to sandbox failed!"
          fi
